name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BenCopp/Streamlit@918e76fcfa09cba0f072064214c868063e2556b0 # This is the action
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: "api-open-classroom" #Must be unique in Heroku
          heroku_email: "benoit.cppn@gmail.com"
          appdir: "API" #
